theme = "custom"

[editor]
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "⭘ NORMAL"
mode.insert = "⏽ INSERT"
mode.select = "⏼ SELECT"
